import type { DetectionResult } from './detector';

/**
 * Generates a production-ready Dockerfile for a Node.js project.
 */
export function generateNodeDockerfile(detection: DetectionResult): string {
  const { hasYarnLock, hasPnpmLock, port, startCommand } = detection;

  let installCmd: string;
  let copyLockfile: string;

  if (hasPnpmLock) {
    installCmd = 'RUN npm install -g pnpm && pnpm install --frozen-lockfile --prod';
    copyLockfile = 'COPY pnpm-lock.yaml ./';
  } else if (hasYarnLock) {
    installCmd = 'RUN yarn install --frozen-lockfile --production';
    copyLockfile = 'COPY yarn.lock ./';
  } else {
    installCmd = 'RUN npm ci --omit=dev';
    copyLockfile = 'COPY package-lock.json* ./';
  }

  return [
    '# Auto-generated by VulnScout AI',
    'FROM node:20-alpine',
    'WORKDIR /app',
    '',
    '# Install dependencies in a separate layer for better caching',
    'COPY package.json ./',
    copyLockfile,
    installCmd,
    '',
    '# Copy application source',
    'COPY . .',
    '',
    `EXPOSE ${port}`,
    `ENV PORT=${port}`,
    '',
    `CMD ["sh", "-c", "${startCommand}"]`,
  ].join('\n');
}

/**
 * Returns a .dockerignore file content to keep the build context lean.
 */
export function generateDockerignore(): string {
  return [
    'node_modules',
    '.git',
    '.gitignore',
    '*.log',
    '.env*',
    'dist',
    'build',
    'coverage',
    '.nyc_output',
    '.DS_Store',
    '*.md',
  ].join('\n');
}
